# Generated by Django 5.1 on 2024-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('ejercicio', models.IntegerField(blank=True, null=True)),
                ('dieta', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
