# Generated by Django 5.1 on 2024-08-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
    ]
