# Generated by Django 5.1 on 2024-08-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_rename_last_name_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
