# Generated by Django 5.1 on 2024-08-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_diet_alter_user_goal_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gym_access',
            field=models.BooleanField(default=False),
        ),
    ]
