# Generated by Django 5.1 on 2024-08-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_usuario_correo_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
