# Generated by Django 5.1 on 2024-08-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'verbose_name': 'Usuario'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
