# Generated by Django 5.1 on 2024-08-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
